import Foundation
import Testing
@testable import MirageKit

/// Cross-engine agreement tests.
///
/// `Resources/golden.json` was generated by `core/mirage/{geo,motion,route}.py` — the
/// implementation that drives the Mac app and is covered by the Python suite. The Swift
/// port asserts against those numbers, so if the two engines ever disagree about where a
/// drive is at t=100s, that shows up here rather than on somebody's phone.
///
/// Regenerate with `scripts/gen-golden.py` after any deliberate change to the Python
/// maths, and expect this suite to fail until the port is updated to match.

// MARK: - Fixtures

private enum MaybeInf: Decodable, Sendable {
    case finite(Double)
    case infinite

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let d = try? c.decode(Double.self) {
            self = .finite(d)
        } else {
            let s = try c.decode(String.self)
            self = s == "inf" ? .infinite : .finite(Double(s) ?? .nan)
        }
    }

    var value: Double {
        switch self {
        case .finite(let d): return d
        case .infinite: return .infinity
        }
    }
}

private struct Golden: Decodable, Sendable {
    struct Pair: Decodable, Sendable { let a: [Double]; let b: [Double]; let m: Double }
    struct Brg: Decodable, Sendable { let a: [Double]; let b: [Double]; let deg: Double }
    struct Dest: Decodable, Sendable { let from: [Double]; let bearing: Double; let m: Double; let to: [Double] }
    struct Triple: Decodable, Sendable { let p: [[Double]]; let r: MaybeInf }
    struct Turn: Decodable, Sendable { let p: [[Double]]; let deg: Double }

    struct PointAt: Decodable, Sendable { let s: Double; let lat: Double; let lon: Double; let heading: Double }
    struct Poly: Decodable, Sendable {
        let points: [[Double]]
        let length: Double
        let segment_lengths: [Double]
        let curvature_radii: [MaybeInf]
        let point_at: [PointAt]
    }

    struct OUStep: Decodable, Sendable { let dt: Double; let east: Double; let north: Double }
    struct OU: Decodable, Sendable {
        let profile: String
        let sigma: Double
        let tau: Double
        let unit_normals: [Double]
        let steps: [OUStep]
    }
    struct ApplyStep: Decodable, Sendable { let dt: Double; let lat: Double; let lon: Double }
    struct OUApply: Decodable, Sendable {
        let sigma: Double
        let tau: Double
        let unit_normals: [Double]
        let origin: [Double]
        let steps: [ApplyStep]
    }

    struct Limits: Decodable, Sendable {
        let v_max: Double; let a_accel: Double; let a_brake: Double
        let a_lateral: Double; let v_min_corner: Double
    }
    struct State: Decodable, Sendable {
        let t: Double; let lat: Double; let lon: Double
        let heading: Double; let speed: Double
    }
    struct Plan: Decodable, Sendable {
        let label: String
        let road_limits: [Double]?
        let expected_travel_time: Double?
        let waypoint_stops: [String: Double]
        let speeds: [Double]
        let arrive: [Double]
        let depart: [Double]
        let total_time: Double
        let distance: Double
        let eta_achievable: Bool
        let state_at: [State]
    }

    let haversine: [Pair]
    let bearing: [Brg]
    let destination: [Dest]
    let circumradius: [Triple]
    let turn_angle: [Turn]
    let polyline: Poly
    let ou: [OU]
    let ou_apply: OUApply
    let limits: Limits
    let plans: [Plan]
}

private let golden: Golden = {
    guard let url = Bundle.module.url(forResource: "golden", withExtension: "json"),
          let data = try? Data(contentsOf: url) else {
        fatalError("golden.json missing from the test bundle")
    }
    return try! JSONDecoder().decode(Golden.self, from: data)
}()

private func ll(_ pair: [Double]) -> LatLon { LatLon(pair[0], pair[1]) }

/// 1e-6 is a tenth of a millimetre in latitude and a micron in metres — far tighter than
/// any difference that could change behaviour, loose enough for libm to vary.
private func close(_ got: Double, _ want: Double, _ tol: Double = 1e-6) -> Bool {
    if got.isInfinite && want.isInfinite { return got.sign == want.sign }
    return abs(got - want) <= tol
}

// MARK: - Geometry

@Suite("Geometry matches the Python engine")
struct GeoGoldenTests {

    @Test("Great-circle distance")
    func haversineMatches() {
        for c in golden.haversine {
            let got = MirageKit.haversine(ll(c.a), ll(c.b))
            #expect(close(got, c.m), "haversine\(c.a)->\(c.b): \(got) vs \(c.m)")
        }
    }

    @Test("Initial bearing, including the wrap Python's modulo gives")
    func bearingMatches() {
        for c in golden.bearing {
            let got = MirageKit.bearing(ll(c.a), ll(c.b))
            #expect(close(got, c.deg), "bearing\(c.a)->\(c.b): \(got) vs \(c.deg)")
        }
    }

    @Test("Destination by bearing and distance")
    func destinationMatches() {
        for c in golden.destination {
            let got = MirageKit.destination(ll(c.from), bearingDegrees: c.bearing, distance: c.m)
            #expect(close(got.lat, c.to[0]), "lat: \(got.lat) vs \(c.to[0])")
            #expect(close(got.lon, c.to[1]), "lon: \(got.lon) vs \(c.to[1])")
        }
    }

    @Test("Turn radius, and infinity for collinear points")
    func circumradiusMatches() {
        for c in golden.circumradius {
            let got = MirageKit.circumradius(ll(c.p[0]), ll(c.p[1]), ll(c.p[2]))
            #expect(close(got, c.r.value, 1e-4), "circumradius: \(got) vs \(c.r.value)")
        }
    }

    @Test("Heading change at a vertex")
    func turnAngleMatches() {
        for c in golden.turn_angle {
            let got = MirageKit.turnAngle(ll(c.p[0]), ll(c.p[1]), ll(c.p[2]))
            #expect(close(got, c.deg), "turnAngle: \(got) vs \(c.deg)")
        }
    }
}

// MARK: - Polyline

@Suite("Arc-length indexing matches the Python engine")
struct PolylineGoldenTests {

    private func poly() throws -> Polyline {
        try Polyline(golden.polyline.points.map(ll))
    }

    @Test("Length and per-segment lengths")
    func lengths() throws {
        let p = try poly()
        #expect(close(p.length, golden.polyline.length, 1e-5))
        let segs = p.segmentLengths()
        #expect(segs.count == golden.polyline.segment_lengths.count)
        for (got, want) in zip(segs, golden.polyline.segment_lengths) {
            #expect(close(got, want, 1e-5))
        }
    }

    @Test("Curvature radius at every vertex")
    func curvature() throws {
        let radii = try poly().curvatureRadii()
        #expect(radii.count == golden.polyline.curvature_radii.count)
        for (got, want) in zip(radii, golden.polyline.curvature_radii) {
            #expect(close(got, want.value, 1e-4), "radius \(got) vs \(want.value)")
        }
    }

    @Test("Point and heading at arc length, including both clamped ends")
    func pointAt() throws {
        let p = try poly()
        for c in golden.polyline.point_at {
            let (pt, hdg) = p.point(at: c.s)
            #expect(close(pt.lat, c.lat), "s=\(c.s) lat: \(pt.lat) vs \(c.lat)")
            #expect(close(pt.lon, c.lon), "s=\(c.s) lon: \(pt.lon) vs \(c.lon)")
            #expect(close(hdg, c.heading), "s=\(c.s) heading: \(hdg) vs \(c.heading)")
        }
    }

    @Test("A polyline needs two distinct points")
    func degenerateInputsRejected() {
        #expect(throws: Polyline.Failure.tooFewPoints) {
            _ = try Polyline([LatLon(51.0, -2.0)])
        }
        // Two points a hair apart collapse to one, which would divide by zero downstream.
        #expect(throws: Polyline.Failure.collapsedToSinglePoint) {
            _ = try Polyline([LatLon(51.0, -2.0), LatLon(51.0, -2.0)])
        }
    }
}

// MARK: - Drift

@Suite("Ornstein-Uhlenbeck drift matches the Python engine")
struct MotionGoldenTests {

    @Test("Decay and increment std, fed the same normals")
    func stepsMatch() {
        for c in golden.ou {
            let ou = OrnsteinUhlenbeck2D(profile: JitterProfile(sigma: c.sigma, tau: c.tau),
                                         noise: FixedNoise(c.unit_normals))
            for s in c.steps {
                let (east, north) = ou.step(s.dt)
                #expect(close(east, s.east), "\(c.profile) dt=\(s.dt) east: \(east) vs \(s.east)")
                #expect(close(north, s.north), "\(c.profile) dt=\(s.dt) north: \(north) vs \(s.north)")
            }
        }
    }

    @Test("Offsets applied to a real coordinate")
    func applyMatches() {
        let c = golden.ou_apply
        let ou = OrnsteinUhlenbeck2D(profile: JitterProfile(sigma: c.sigma, tau: c.tau),
                                     noise: FixedNoise(c.unit_normals))
        for s in c.steps {
            let p = ou.apply(to: ll(c.origin), dt: s.dt)
            #expect(close(p.lat, s.lat), "dt=\(s.dt) lat: \(p.lat) vs \(s.lat)")
            #expect(close(p.lon, s.lon), "dt=\(s.dt) lon: \(p.lon) vs \(s.lon)")
        }
    }

    @Test("The named profiles carry the tuned values")
    func profilesMatch() {
        #expect(JitterProfile.named("stationary") == JitterProfile(sigma: 4.5, tau: 30.0))
        #expect(JitterProfile.named("walking") == JitterProfile(sigma: 5.0, tau: 15.0))
        #expect(JitterProfile.named("driving") == JitterProfile(sigma: 3.0, tau: 10.0))
        #expect(JitterProfile.named("indoors") == JitterProfile(sigma: 12.0, tau: 45.0))
        #expect(JitterProfile.named("nonsense") == nil)
    }

    @Test("A long gap does not blow the drift up — the resumed-session case")
    func longGapStaysBounded() {
        // iPhone suspends apps, so a resumed tick can arrive minutes late. The exact
        // discrete-time solution keeps the stationary std correct for any dt; an Euler
        // step would not.
        let ou = OrnsteinUhlenbeck2D(profile: .stationary, noise: FixedNoise([3.0]))
        let (east, north) = ou.step(3600.0)
        #expect(abs(east) <= 4.5 * 3.0 + 1e-9)
        #expect(abs(north) <= 4.5 * 3.0 + 1e-9)
    }
}

// MARK: - Trajectory

@Suite("Drive plans match the Python engine")
struct RouteGoldenTests {

    @Test("Default vehicle limits are the same numbers")
    func limitsMatch() {
        let l = VehicleLimits()
        #expect(close(l.vMax, golden.limits.v_max))
        #expect(close(l.aAccel, golden.limits.a_accel))
        #expect(close(l.aBrake, golden.limits.a_brake))
        #expect(close(l.aLateral, golden.limits.a_lateral))
        #expect(close(l.vMinCorner, golden.limits.v_min_corner))
    }

    /// `includeStops: false` throughout: the junction model is the one deliberately
    /// non-portable piece, because reproducing Python's Mersenne Twister would buy
    /// nothing. Everything deterministic is pinned here.
    @Test("Speeds, timings and interpolated state for every planning case")
    func plansMatch() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))

        for c in golden.plans {
            var stops: [Int: Double] = [:]
            for (k, v) in c.waypoint_stops { stops[Int(k)!] = v }

            let plan = buildPlan(poly,
                                 expectedTravelTime: c.expected_travel_time,
                                 includeStops: false,
                                 waypointStops: stops,
                                 roadLimits: c.road_limits)

            #expect(plan.speeds.count == c.speeds.count, "\(c.label): speed count")
            for (i, want) in c.speeds.enumerated() {
                #expect(close(plan.speeds[i], want, 1e-5), "\(c.label) speeds[\(i)]")
            }
            for (i, want) in c.arrive.enumerated() {
                #expect(close(plan.arrive[i], want, 1e-5), "\(c.label) arrive[\(i)]")
            }
            for (i, want) in c.depart.enumerated() {
                #expect(close(plan.depart[i], want, 1e-5), "\(c.label) depart[\(i)]")
            }
            #expect(close(plan.totalTime, c.total_time, 1e-5), "\(c.label) totalTime")
            #expect(close(plan.distance, c.distance, 1e-5), "\(c.label) distance")
            #expect(plan.etaAchievable == c.eta_achievable, "\(c.label) etaAchievable")

            for s in c.state_at {
                let got = plan.state(at: s.t)
                #expect(close(got.point.lat, s.lat, 1e-6), "\(c.label) t=\(s.t) lat")
                #expect(close(got.point.lon, s.lon, 1e-6), "\(c.label) t=\(s.t) lon")
                #expect(close(got.heading, s.heading, 1e-6), "\(c.label) t=\(s.t) heading")
                #expect(close(got.speed, s.speed, 1e-5), "\(c.label) t=\(s.t) speed")
            }
        }
    }

    @Test("An impossible ETA is reported, not silently driven at 1200 km/h")
    func impossibleETAIsClamped() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        let plan = buildPlan(poly, expectedTravelTime: 20.0, includeStops: false)
        #expect(plan.etaAchievable == false)
        #expect(plan.totalTime > 20.0)
        #expect(plan.speeds.allSatisfy { $0 <= VehicleLimits().vMax + 1e-9 })
    }

    @Test("A user's stop is added on top of Apple's estimate, not scaled into it")
    func waypointStopsAddOnTop() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        let plain = buildPlan(poly, expectedTravelTime: 400.0, includeStops: false)
        let stopped = buildPlan(poly, expectedTravelTime: 400.0, includeStops: false,
                                waypointStops: [3: 120.0])
        #expect(close(stopped.totalTime - plain.totalTime, 120.0, 1e-5))
    }

    @Test("A road speed limit caps the solver, however optimistic the estimate")
    func roadLimitsCapSpeed() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        // 30 km/h everywhere. Without this the solver happily does 120 on a side street,
        // which is a far louder tell than any amount of traffic modelling fixes.
        let thirty = [Double](repeating: 30.0 / 3.6, count: poly.count)

        let unlimited = buildPlan(poly, expectedTravelTime: 60, includeStops: false)
        let limited = buildPlan(poly, expectedTravelTime: 60, includeStops: false,
                                roadLimits: thirty)

        // The ceiling is the posted limit plus the allowance a real driver takes, not the
        // posted limit itself — see `speedingAllowanceApplies`. What matters here is that
        // an estimate demanding 120 km/h cannot push a vertex past it: the allowance is a
        // fixed margin over the sign, never a licence to drive at whatever the ETA wants.
        let ceiling = 30.0 / 3.6 + VehicleLimits().speedingAllowance
        #expect(limited.speeds.allSatisfy { $0 <= ceiling + 1e-9 })
        #expect(limited.totalTime > unlimited.totalTime)
        #expect(limited.etaAchievable == false, "60s is not possible at 30 km/h; say so")
    }

    @Test("A vertex with no known limit falls back to the vehicle ceiling")
    func unknownLimitsFallBack() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        // 0 means "no limit known here" — OSM leaves maxspeed off most ways.
        let none = [Double](repeating: 0, count: poly.count)
        let a = buildPlan(poly, includeStops: false)
        let b = buildPlan(poly, includeStops: false, roadLimits: none)
        #expect(a.speeds == b.speeds)
    }

    @Test("Drivers sit a little over the limit when the road is clear")
    func speedingAllowanceApplies() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        let fifty = [Double](repeating: 50 / 3.6, count: poly.count)

        // No estimate at all means no traffic information, so the full allowance applies.
        let plan = buildPlan(poly, includeStops: false, roadLimits: fifty)
        let peak = plan.speeds.max() ?? 0

        #expect(peak > 50 / 3.6, "driving a whole route at exactly the limit is its own tell")
        #expect(peak <= (50 + 8.001) / 3.6, "but only a little over, not a free-for-all")
    }

    @Test("Nobody speeds in a queue")
    func congestionRemovesTheAllowance() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        let fifty = [Double](repeating: 50 / 3.6, count: poly.count)

        let clear = buildPlan(poly, includeStops: false, roadLimits: fifty)
        let freeFlow = clear.totalTime

        // An estimate far longer than free-flow is what congestion looks like through the
        // one signal Apple gives us.
        let jammed = buildPlan(poly, expectedTravelTime: freeFlow * 3,
                               includeStops: false, roadLimits: fifty)

        #expect((jammed.speeds.max() ?? 0) < 50 / 3.6, "a queue does not exceed the limit")
        #expect(jammed.totalTime > clear.totalTime)
    }

    @Test("The allowance needs a known limit to be relative to")
    func noAllowanceWithoutALimit() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        // Nothing known anywhere: the vehicle ceiling still governs, unchanged.
        let a = buildPlan(poly, includeStops: false)
        let b = buildPlan(poly, includeStops: false,
                          roadLimits: [Double](repeating: 0, count: poly.count))
        #expect(a.speeds == b.speeds)
        #expect((a.speeds.max() ?? 0) <= VehicleLimits().vMax + 1e-9)
    }

    @Test("The junction model is seeded, so one engine reproduces itself")
    func junctionDwellsAreDeterministic() throws {
        let poly = try Polyline(golden.polyline.points.map(ll))
        let a = buildPlan(poly, includeStops: true, waypointStops: [:])
        let b = buildPlan(poly, includeStops: true, waypointStops: [:])
        #expect(a.totalTime == b.totalTime)
    }
}
